### PR TITLE
feat: disable winbar when there are no pending tasks

### PR DESCRIPTION
**Pull request by shawnyu5**
Having an empty winbar bothers me. So the winbar will be set to an empty value if there are no pending tasks.

This is mostly complete, apart from a few edge cases, which still needs a bit of testing

### CODE REVIEW

**Comment by shawnyu5** [comment]
Gonna add some tests here as well

**Comment by nocksock** [comment]
Whoa! Going to read through it now. Quite a bunch of changes. :D 
Didn't get a notification for the PR - will have to look into that too.

**Comment by shawnyu5** [comment]
I've been using this branch for the past few days. Everything seems to work pretty well. There does seem to be a few edge cases, mostly with `:DoToggle` that I should look at. I also gotta clean up the code a bit, but this mostly works

**Comment by nocksock** [comment]
when I have split windows, this re-introduces jumpy text eg. when having a split, and having the cursor on top, the text jumps when moving from one window to the next. I thought I had this fixed. Will look into it.

**Comment by shawnyu5** [comment]
Okay, fixed the issue with `:DoEdit` being weird. Also, the cursor jumping seems to have been fixed with the winbar implementation itself?

Can you take a peek at everything. This branch has been working pretty well for me

**Comment by shawnyu5** [comment]
Also, wantta throw the hacktober fest tag on this repo :astonished:

**Comment by nocksock** [comment]
FYI, in case the other PR didn't trigger some kind of notification: I created #4, which includes all of this and some of my own changes. Thanks for all the work so far! 

> Also, wantta throw the hacktober fest tag on this repo 😲

Done :D

**Comment by nocksock** [comment]
@shawnyu5 sorry it took that long to get your contributions into main. It's now all merged! Thank you so much, again! :)

**Pull request merged**
